site_name: KjG MiDa - Vergleich von existierenden Softwarelösungen
site_url: https://kjg-bad-abbach.github.io/kjg-mida-comparison/
theme:
  name: material
  palette:
    primary: cyan
    accent: teal
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    # - navigation.indexes
    - toc.follow
    - toc.integrate
    - search.suggest
markdown_extensions:
  - attr_list
plugins:
  - search:
      separator: '[^\w]+'
      lang: de
