name: mkdocs-deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}-pnpm-${{ hashFiles('image-link-optimizer/pnpm-lock.yaml') }}
          path: |
            .cache
            image-link-optimizer/node_modules
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: 'image-link-optimizer/pnpm-lock.yaml'
      - run: cd image-link-optimizer && pnpm install && pnpm optimize-images && cd ..
      - run: mkdocs gh-deploy --force
